name: Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install build package
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build package
      run: python -m build
    - name: Get version from file
      run: |
        VER=$(cat version)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Install locally to test
      run: python -m pip install ./dist/circuiteml-${{ env.VERSION }}.tar.gz
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
    - name: Install Pacakage from pypi
      run: python -m pip install circuiteml
      
      
